version: 2.1

executors:
  py310:
    docker:
      - image: cimg/python:3.10
  py312:
    docker:
      - image: cimg/python:3.12

jobs:
  run_tests:
    parameters:
      python_version:
        type: executor
      django_version:
        type: string
    executor: << parameters.python_version >>
    steps:
      - checkout
      - run:
          name: Install HTML Tidy
          command: |
            wget https://github.com/htacg/tidy-html5/releases/download/5.8.0/tidy-5.8.0-Linux-64bit.deb && sudo dpkg -i tidy-5.8.0-Linux-64bit.deb
            rm -rf tidy-5.8.0-Linux-64bit.deb
      - run:
          name: Install Requirements
          command: |
            pip install .[dev,ci]
      - run:
          name: Install Django << parameters.django_version >>
          command: |
            pip install "django<< parameters.django_version >>"
      - run:
          name: Django Checks
          command: |
            python manage.py check
      - run:
          name: Black
          command: |
            black . --check
      - run:
          name: Curly Lint
          command: | 
            curlylint .
      - run:
          name: Ruff lint
          command: |  
            ruff check .
      - run:
          name: Ruff Format
          command: | 
            ruff format .
      - run: mkdir -p test-results
      - run:
          name: Pytest
          command: |
            pytest --junitxml=test-results/junit.xml -o junit_family=legacy -sx
      - store_test_results:
          path: test-results

workflows:
  tests:
    jobs:
      - run_tests:

          matrix:
            parameters:
              python_version: [ py310, py312 ]
              django_version: [ ">=3.2,<4.0", ">=4.0,<4.1", ">=4.1,<4.2" ]

